export const createTables = [
    `CREATE TABLE IF NOT EXISTS NCRForm (
        id INTEGER PRIMARY KEY,
        CreationDate datetime NOT NULL,
        LastModified datetime NOT NULL,
        FormStatus STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS Role (
        id INTEGER PRIMARY KEY,
        Title STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS User (
        id INTEGER PRIMARY KEY,
        FName STRING NOT NULL,
        MName STRING,
        LName STRING NOT NULL,
        Email STRING NOT NULL UNIQUE,
        Password STRING NOT NULL,
        RoleID INTEGER NOT NULL,
        FOREIGN KEY(RoleID) REFERENCES Role(id)
    )`,
    `CREATE TABLE IF NOT EXISTS FormUsers (
        NCRFormID INTEGER NOT NULL,
        UserID INTEGER NOT NULL,
        PRIMARY KEY (NCRFormID, UserID),
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id) ON DELETE CASCADE,
        FOREIGN KEY (UserID) REFERENCES User(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS Supplier (
        id INTEGER PRIMARY KEY,
        SupplierName STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS Product (
        id INTEGER PRIMARY KEY,
        ProductName STRING NOT NULL,
        Number INTEGER NOT NULL UNIQUE,
        SupplierID INTEGER NOT NULL,
        FOREIGN KEY (SupplierID) REFERENCES Supplier(id)
    )`,
    `CREATE TABLE IF NOT EXISTS Quality (
        NCRFormID INTEGER PRIMARY KEY,
        NCRNumber STRING NOT NULL,
        SRInspection BOOLEAN NOT NULL,
        WorkInProgress BOOLEAN NOT NULL,
        ItemDescription STRING NOT NULL,
        QuantityReceived INTEGER NOT NULL,
        QuantityDefective INTEGER NOT NULL,
        IsNonConforming BOOLEAN NOT NULL,
        Details STRING NOT NULL,
        QualityStatus STRING NOT NULL,
        LastModified DATETIME NOT NULL,
        ProductID INTEGER NOT NULL,
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id),
        FOREIGN KEY (ProductID) REFERENCES Product(id)
    )`,
    `CREATE TABLE IF NOT EXISTS Engineer (
        NCRFormID INTEGER PRIMARY KEY,
        Review STRING NOT NULL,
        NotifyCustomer BOOLEAN NOT NULL,
        Disposition STRING NOT NULL,
        RevisionNumber STRING,
        RevisionDate DATETIME,
        EngineerStatus STRING NOT NULL,
        LastModified DATETIME NOT NULL,
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id)
    )`
];

export const dropTables = [
    'DROP TABLE IF EXISTS FormUsers',
    'DROP TABLE IF EXISTS Quality',
    'DROP TABLE IF EXISTS Engineer',
    'DROP TABLE IF EXISTS Product',
    'DROP TABLE IF EXISTS Supplier',
    'DROP TABLE IF EXISTS User',
    'DROP TABLE IF EXISTS Role',
    'DROP TABLE IF EXISTS NCRForm'
];

export const seedTables = [
    `INSERT INTO Role (Title) VALUES 
        ('Admin'),
        ('Inspector'),
        ('Engineer')`,
    `INSERT INTO User (FName, MName, LName, Email, Password, RoleID) VALUES 
        ('Alan', 'W', 'Wake', 'alan.wake@crossfire.ca', 'password123', 1), 
        ('Parappa', 'tha', 'Rappa', 'parappa.rappa@crossfire.ca', 'password123', 2), 
        ('Cave', 'G', 'Johnson', 'cave.johnson@crossfire.ca', 'password123', 3),
        ('Alduin', 'Twilight', 'World Eater', 'admin@crossfire.ca', 'admin', 1)`,
    `INSERT INTO NCRForm (CreationDate, LastModified, FormStatus) VALUES 
        ('2024-10-01', '2024-10-02', 'Closed'), 
        ('2024-10-03', '2024-10-04', 'Closed'), 
        ('2024-10-05', '2024-10-06', 'Closed'),
        ('2024-10-07', '2024-10-08', 'Open'),
        ('2024-10-09', '2024-10-10', 'Open'),
        ('2024-10-11', '2024-10-12', 'Closed'),
        ('2024-10-13', '2024-10-14', 'Open'),
        ('2024-10-15', '2024-10-16', 'Open'),
        ('2024-10-17', '2024-10-18', 'Open'),
        ('2024-10-19', '2024-10-20', 'Open')`,
    `INSERT INTO FormUsers (NCRFormID, UserID) VALUES 
        (1, 1), 
        (1, 2), 
        (2, 3), 
        (3, 4),
        (4, 1),
        (5, 2),
        (6, 3),
        (7, 4),
        (8, 1),
        (9, 2),
        (10, 3)`,
    `INSERT INTO Supplier (SupplierName) VALUES 
        ('Ace Fasteners'), 
        ('Best Bolts Co.'), 
        ('HomePro Tools'), 
        ('Reliable Paints'),
        ('Grainger'),
        ('Fastenal'),
        ('MSC Industrial Supply'),
        ('Airgas'), ('HD Supply'),
        ('Applied Industrial Technologies'),
        ('Motion Industries'),
        ('Parker Hannifin'),
        ('Kaman Industrial Technologies'),
        ('W.W. Williams'),
        ('Ingersoll Rand'),
        ('Reliance Electric'),
        ('Eaton Corporation'),
        ('3M'),('Emerson Electric'),
        ('Siemens'),
        ('ABB'),
        ('Rexel'),
        ('Ferguson'),
        ('Graybar'), 
        ('Top Electrical Supplies')`,
    `INSERT INTO Product (ProductName, Number, SupplierID) VALUES
                ('Ball Bearing', '834', '7'),
                ('Steel Pipe', '562', '12'),
                ('Hydraulic Pump', '299', '15'),
                ('Industrial Fan', '129', '6'),
                ('Electric Motor', '453', '14'),
                ('Air Compressor', '378', '9'),
                ('Welding Machine', '274', '3'),
                ('Safety Gloves', '651', '10'),
                ('Conveyor Belt', '569', '4'),
                ('Pressure Gauge', '183', '16'),
                ('Industrial Hose', '432', '8'),
                ('Circuit Breaker', '119', '19'),
                ('LED Work Light', '506', '5'),
                ('Lubricant Oil', '211', '13'),
                ('Gear Reducer', '743', '20'),
                ('Pneumatic Cylinder', '928', '7'),
                ('Torque Wrench', '335', '11'),
                ('Safety Helmet', '484', '2'),
                ('Power Supply Unit', '626', '6'),
                ('Filter Cartridge', '235', '10'),
                ('Welding Rod', '372', '4'),
                ('Sprocket Gear', '818', '12'),
                ('Industrial Valve', '596', '9'),
                ('Hand Tool Set', '219', '15'),
                ('Bearing Grease', '753', '8'),
                ('Hydraulic Oil', '102', '5'),
                ('Protective Goggles', '618', '11'),
                ('V-Belt', '358', '3'),
                ('Control Panel', '480', '17'),
                ('Lifting Chain', '705', '2'),
                ('Electric Drill', '823', '14'),
                ('Industrial Fasteners', '369', '18'),
                ('Pipe Fittings', '291', '7'),
                ('Steel Cable', '745', '19'),
                ('Work Boots', '631', '12'),
                ('Cooling Fan', '590', '16'),
                ('Cutting Disc', '197', '9'),
                ('Battery Charger', '863', '4'),
                ('Industrial Adhesive', '534', '13'),
                ('Ball Valve', '402', '8'),
                ('Wrench Set', '342', '10'),
                ('Gas Cylinder', '216', '1'),
                ('Rubber Gasket', '155', '6'),
                ('Air Filter', '694', '20'),
                ('Hose Clamps', '118', '3'),
                ('Safety Mask', '853', '15'),
                ('Roller Chain', '217', '5'),
                ('Industrial Hammer', '477', '11'),
                ('Tool Box', '269', '18'),
                ('Grinder Disc', '685', '7'),
                ('Angle Grinder', '538', '9'),
                ('Sealing Tape', '407', '14'),
                ('Pipe Wrench', '972', '8'),
                ('Hydraulic Jack', '502', '13'),
                ('Industrial Tape', '401', '2'),
                ('Heat Gun', '648', '4'),
                ('Pallet Jack', '214', '16'),
                ('Electric Saw', '537', '12'),
                ('Pressure Washer', '873', '10'),
                ('Cutting Oil', '439', '6'),
                ('Industrial Pulley', '178', '20'),
                ('Socket Set', '496', '1'),
                ('Machine Oil', '738', '17'),
                ('Safety Vest', '983', '11'),
                ('Handheld Radio', '691', '5'),
                ('Grinding Wheel', '294', '9'),
                ('Plastic Container', '825', '7'),
                ('Welding Helmet', '167', '15'),
                ('Impact Drill', '782', '14'),
                ('Rubber Mat', '597', '8'),
                ('PPE Kit', '202', '3'),
                ('Air Blower', '452', '18'),
                ('Locking Pliers', '629', '10'),
                ('Industrial Fan Belt', '331', '13'),
                ('Sandpaper Roll', '914', '19'),
                ('Extension Cord', '573', '6'),
                ('Oil Filter', '157', '5'), 
                ('Hydraulic Hose', '912', '4'),
                ('Tool Belt', '413', '12'),
                ('Lifting Strap', '678', '8'),
                ('Hand Saw', '287', '16'),
                ('Safety Harness', '923', '2'),
                ('Cleaning Brush', '492', '9'),
                ('Industrial Cleaner', '734', '11'),
                ('Storage Bin', '599', '4'),
                ('Metal File', '284', '15'),
                ('Work Light', '856', '10'),
                ('Grease Gun', '320', '3'),
                ('Tool Cart', '765', '7'),
                ('Chain Hoist', '509', '20'),
                ('Hearing Protection', '476', '13'),
                ('Rubber Gloves', '512', '6'),
                ('Dust Mask', '670', '19'),
                ('Work Apron', '839', '14'),
                ('Utility Knife', '491', '17'),
                ('Pallet Rack', '303', '12'),
                ('Wire Stripper', '918', '5'),
                ('Grease Fitting', '175', '18'),
                ('Metal Clamp', '463', '1'),
                ('Tool Organizer', '105', '6')`,
    `INSERT INTO Quality (NCRFormID, NCRNumber, SRInspection, WorkInProgress, ItemDescription, QuantityReceived, QuantityDefective, IsNonConforming, Details, QualityStatus, LastModified, ProductID) VALUES 
                (1, '2024-001', 1, 0, 'Industrial Hammer', 50, 5, 1, 'Loose hammer handles on 5 units.', 'Closed', '2024-10-02', 48), 
                (2, '2024-002', 0, 1, 'Impact Drill', 30, 3, 1, '3 drills with faulty motors.', 'Closed', '2024-10-04', 69), 
                (3, '2024-003', 1, 0, 'Safety Mask', 100, 25, 1, 'Mask straps are broken', 'Closed', '2024-10-06', 46),
                (4, '2024-004', 0, 1, 'Safety Harness', 10, 3, 1, 'Clasps are broken', 'Open', '2024-10-08', 82),
                (5, '2024-005', 1, 0, 'Tool Box', 5, 1, 1, 'Hinge is broken on 1 unit', 'Open', '2024-10-10', 49),
                (6, '2024-006', 0, 1, 'Sealing Tape', 250, 1, 1, 'Tape isnt sticky', 'Closed', '2024-10-12', 52),
                (7, '2024-007', 1, 0, 'Ball Bearing', 100, 20, 1, 'Bearings arent correcly assembled', 'Open', '2024-10-14', 1),
                (8, '2024-008', 0, 1, 'Industrial Hose', 20, 1, 1, 'Hose has a hole in it', 'Open', '2024-10-16', 11),
                (9, '2024-009', 1, 0, 'Safety Helmet', 50, 5, 1, 'Helmets arent the right colour', 'Open', '2024-10-18', 18),
                (10, '2024-010', 0, 1, 'Hydraulic Oil', 100, 50, 1, 'Recieved AW46 oil instead of the AW32 oil', 'Open', '2024-10-20', 26)`,
`INSERT INTO Engineer (NCRFormID, Review, NotifyCustomer, Disposition, RevisionNumber, RevisionDate, EngineerStatus, LastModified) VALUES 
                (1, 'Rework', 0, 'Accepted with Rework', '399-B', '2024-10-03', 'Closed', '2024-10-02'), 
                (2, 'Scrap', 1, 'Rejected', NULL, NULL, 'Closed', '2024-10-04'), 
                (3, 'Repair', 0, 'Approved', '456-C', '2024-10-07', 'Closed', '2024-10-06'), 
                (4, 'Repair', 0, 'Approved', NULL, NULL, 'Open', '2024-10-09'), 
                (5, 'Repair', 1, 'Approved', NULL, NULL, 'Open', '2024-10-12'), 
                (6, 'Scrap', 1, 'Approved', '354-A', '2024-10-13', 'Closed', '2024-10-13'), 
                (7, 'Rework', 0, 'Approved', '576-B', '2024-10-16', 'Open', '2024-10-16'), 
                (8, 'Scrap', 1, 'Approved', '234-A', '2024-10-17', 'Open', '2024-10-18'), 
                (9, 'Use As Is', 0, 'Approved', NULL, NULL, 'Open', '2024-10-18'), 
                (10, 'Rework', 1, 'Approved with rework', NULL, NULL, 'Open', '2024-10-22')`,
];