export const createTables = [
    `CREATE TABLE IF NOT EXISTS NCRForm (
        id INTEGER PRIMARY KEY,
        CreationDate datetime NOT NULL,
        LastModified datetime NOT NULL,
        FormStatus STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS Role (
        id INTEGER PRIMARY KEY,
        Title STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS User (
        id INTEGER PRIMARY KEY,
        FName STRING NOT NULL,
        MName STRING,
        LName STRING NOT NULL,
        Email STRING NOT NULL UNIQUE,
        Password STRING NOT NULL,
        RoleID INTEGER NOT NULL,
        FOREIGN KEY(RoleID) REFERENCES Role(id)
    )`,
    `CREATE TABLE IF NOT EXISTS FormUsers (
        NCRFormID INTEGER NOT NULL,
        UserID INTEGER NOT NULL,
        PRIMARY KEY (NCRFormID, UserID),
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id) ON DELETE CASCADE,
        FOREIGN KEY (UserID) REFERENCES User(id) ON DELETE CASCADE
    )`,
    `CREATE TABLE IF NOT EXISTS Supplier (
        id INTEGER PRIMARY KEY,
        Name STRING NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS Product (
        id INTEGER PRIMARY KEY,
        Name STRING NOT NULL,
        Number INTEGER NOT NULL,
        SupplierID INTEGER NOT NULL,
        FOREIGN KEY (SupplierID) REFERENCES Supplier(id)
    )`,
    `CREATE TABLE IF NOT EXISTS Quality (
        NCRFormID INTEGER PRIMARY KEY,
        NCRNumber STRING NOT NULL,
        SRInspection BOOLEAN NOT NULL,
        WorkInProgress BOOLEAN NOT NULL,
        ItemDescription STRING NOT NULL,
        QuantityReceived INTEGER NOT NULL,
        QuantityDefective INTEGER NOT NULL,
        IsNonConforming BOOLEAN NOT NULL,
        Details STRING NOT NULL,
        LastModified DATETIME NOT NULL,
        ProductID INTEGER NOT NULL,
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id),
        FOREIGN KEY (ProductID) REFERENCES Product(id)
    )`,
    `CREATE TABLE IF NOT EXISTS Engineer (
        NCRFormID INTEGER PRIMARY KEY,
        Disposition STRING NOT NULL,
        DrawingUpdateRequired BOOLEAN NOT NULL,
        CurrentRevisionNumber INTEGER,
        NewRevisionNumber INTEGER,
        RevisionDate DATETIME,
        LastModified DATETIME NOT NULL,
        FOREIGN KEY (NCRFormID) REFERENCES NCRForm(id)
    )`
];

export const seedTables = [
    `INSERT INTO Role (Title) VALUES 
        ('Admin'),
        ('Engineer'), 
        ('Inspector')`,
    `INSERT INTO User (FName, MName, LName, Email, Password, RoleID) VALUES 
        ('Alan', 'W', 'Wake', 'alan.wake@example.com', 'password123', 1), 
        ('Parappa', 'tha', 'Rappa', 'parappa.rappa@example.com', 'password123', 2), 
        ('Cave', 'G', 'Johnson', 'cave.johnson@example.com', 'password123', 3),
        ('Alduin', 'Twilight', 'World Eater', 'alduin.worldeater@example.com', 'password123', 3)`,
    `INSERT INTO NCRForm (CreationDate, LastModified, FormStatus) VALUES 
        ('2024-10-01', '2024-10-02', 'Open'), 
        ('2024-10-03', '2024-10-04', 'Open'), 
        ('2024-10-05', '2024-10-06', 'Closed')`,
    `INSERT INTO FormUsers (NCRFormID, UserID) VALUES 
        (1, 1), 
        (1, 2), 
        (2, 3), 
        (3, 4)`,
    `INSERT INTO Supplier (Name) VALUES 
        ('Ace Fasteners'), 
        ('Best Bolts Co.'), 
        ('HomePro Tools'), 
        ('Reliable Paints'),
        ('Grainger'),
        ('Fastenal'),
        ('MSC Industrial Supply'),
        ('Airgas'), ('HD Supply'),
        ('Applied Industrial Technologies'),
        ('Motion Industries'),
        ('Parker Hannifin'),
        ('Kaman Industrial Technologies'),
        ('W.W. Williams'),
        ('Ingersoll Rand'),
        ('Reliance Electric'),
        ('Eaton Corporation'),
        ('3M'),('Emerson Electric'),
        ('Siemens'),
        ('ABB'),
        ('Rexel'),
        ('Ferguson'),
        ('Graybar'), 
        ('Top Electrical Supplies')`,
    `INSERT INTO Product (Name, Number, SupplierID) VALUES
        ('Ball Bearing', '834', '7'),
        ('Steel Pipe', '562', '12'),
        ('Hydraulic Pump', '291', '15'),
        ('Industrial Fan', '129', '6'),
        ('Electric Motor', '452', '14'),
        ('Air Compressor', '378', '9'),
        ('Welding Machine', '274', '3'),
        ('Safety Gloves', '651', '10'),
        ('Conveyor Belt', '597', '4'),
        ('Pressure Gauge', '183', '16'),
        ('Industrial Hose', '432', '8'),
        ('Circuit Breaker', '119', '19'),
        ('LED Work Light', '506', '5'),
        ('Lubricant Oil', '211', '13'),
        ('Gear Reducer', '743', '20'),
        ('Pneumatic Cylinder', '928', '7'),
        ('Torque Wrench', '335', '11'),
        ('Safety Helmet', '484', '2'),
        ('Power Supply Unit', '626', '6'),
        ('Filter Cartridge', '235', '10'),
        ('Welding Rod', '372', '4'),
        ('Sprocket Gear', '818', '12'),
        ('Industrial Valve', '596', '9'),
        ('Hand Tool Set', '219', '15'),
        ('Bearing Grease', '753', '8'),
        ('Hydraulic Oil', '102', '5'),
        ('Protective Goggles', '618', '11'),
        ('V-Belt', '358', '3'),
        ('Control Panel', '480', '17'),
        ('Lifting Chain', '705', '2'),
        ('Electric Drill', '823', '14'),
        ('Industrial Fasteners', '369', '18'),
        ('Pipe Fittings', '291', '7'),
        ('Steel Cable', '745', '19'),
        ('Work Boots', '631', '12'),
        ('Cooling Fan', '590', '16'),
        ('Cutting Disc', '197', '9'),
        ('Battery Charger', '863', '4'),
        ('Industrial Adhesive', '534', '13'),
        ('Ball Valve', '402', '8'),
        ('Wrench Set', '342', '10'),
        ('Gas Cylinder', '214', '1'),
        ('Rubber Gasket', '155', '6'),
        ('Air Filter', '691', '20'),
        ('Hose Clamps', '118', '3'),
        ('Safety Mask', '853', '15'),
        ('Roller Chain', '214', '5'),
        ('Industrial Hammer', '477', '11'),
        ('Tool Box', '269', '18'),
        ('Grinder Disc', '685', '7'),
        ('Angle Grinder', '538', '9'),
        ('Sealing Tape', '407', '14'),
        ('Pipe Wrench', '972', '8'),
        ('Hydraulic Jack', '502', '13'),
        ('Industrial Tape', '401', '2'),
        ('Heat Gun', '648', '4'),
        ('Pallet Jack', '214', '16'),
        ('Electric Saw', '537', '12'),
        ('Pressure Washer', '873', '10'),
        ('Cutting Oil', '439', '6'),
        ('Industrial Pulley', '178', '20'),
        ('Socket Set', '496', '1'),
        ('Machine Oil', '738', '17'),
        ('Safety Vest', '983', '11'),
        ('Handheld Radio', '691', '5'),
        ('Grinding Wheel', '294', '9'),
        ('Plastic Container', '825', '7'),
        ('Welding Helmet', '167', '15'),
        ('Impact Drill', '782', '14'),
        ('Rubber Mat', '597', '8'),
        ('PPE Kit', '202', '3'),
        ('Air Blower', '452', '18'),
        ('Locking Pliers', '629', '10'),
        ('Industrial Fan Belt', '331', '13'),
        ('Sandpaper Roll', '914', '19'),
        ('Extension Cord', '573', '6'),
        ('Oil Filter', '157', '5'), 
        ('Hydraulic Hose', '912', '4'),
        ('Tool Belt', '413', '12'),
        ('Lifting Strap', '678', '8'),
        ('Hand Saw', '287', '16'),
        ('Safety Harness', '923', '2'),
        ('Cleaning Brush', '492', '9'),
        ('Industrial Cleaner', '734', '11'),
        ('Storage Bin', '599', '4'),
        ('Metal File', '284', '15'),
        ('Work Light', '856', '10'),
        ('Grease Gun', '320', '3'),
        ('Tool Cart', '765', '7'),
        ('Chain Hoist', '509', '20'),
        ('Hearing Protection', '476', '13'),
        ('Rubber Gloves', '512', '6'),
        ('Dust Mask', '670', '19'),
        ('Work Apron', '839', '14'),
        ('Utility Knife', '491', '17'),
        ('Pallet Rack', '303', '12'),
        ('Wire Stripper', '918', '5'),
        ('Grease Fitting', '175', '18'),
        ('Metal Clamp', '463', '1'),
        ('Tool Organizer', '104', '6')`,
    `INSERT INTO Quality (NCRFormID, NCRNumber, SRInspection, WorkInProgress, ItemDescription, QuantityReceived, QuantityDefective, IsNonConforming, Details, LastModified, ProductID) VALUES 
        (1, 'NCR001', 1, 0, 'Hammer - Handle loose', 50, 5, 1, 'Loose hammer handles on 5 units.', '2024-10-02', 1), 
        (2, 'NCR002', 0, 1, 'Drill - Motor issue', 30, 3, 1, '3 drills with faulty motors.', '2024-10-04', 2), 
        (3, 'NCR003', 1, 0, 'Paint Can - Lid issues', 100, 7, 1, 'Paint can lids not sealing properly.', '2024-10-06', 3)`,
    `INSERT INTO Engineer (NCRFormID, Disposition, DrawingUpdateRequired, CurrentRevisionNumber, NewRevisionNumber, RevisionDate, LastModified) VALUES 
        (1, 'Accepted with Rework', 1, 1, 2, '2024-10-03', '2024-10-02'), 
        (2, 'Rejected', 0, 1, NULL, NULL, '2024-10-04'), 
        (3, 'Approved', 1, 2, 3, '2024-10-07', '2024-10-06')`
];